### ISSUE TITLE
Breaking change from 0.1.7 to 0.1.9 TypeError: Arguments to path.resolve must be strings.

### ISSUE THREAD

**Issue by dsandor** [coreybutler/node-windows#104]
Was using 0.1.7.  Updated to 0.1.9 and now service won't start.  I ran the command line manually:
--harmony "..../wrapper.js" -f myscript -l myappname ...

This works if I downgrade to 0.1.7 but fails with the error listed below on 0.1.9.
TypeError: Arguments to path.resolve must be strings.

**Comment by fmatoss** [comment]
Look https://github.com/coreybutler/node-windows/issues/103

**Comment by dsandor** [comment]
Fix for #103 fixed this issue.
