### ISSUE TITLE
did somebody get this work in an electron app?

### ISSUE THREAD

**Issue by mnewmedia** [coreybutler/node-windows#110]
It does install it, but not start it. When I try to start it manually in the service manager it get's stopped again after a second.

**Comment by coreybutler** [comment]
Node-windows shouldn't be used to run an electron app... electron has it's own process management. 

If you're trying to use node-windows within an electron app to create new services outside of electron, then you have to be particularly careful with permissions. Also remember that electron still uses iojs, which has a different executable than node-windows. Until electron upgrades to one of the new node 4.x versions, it is unlikely node-windows would be able to spawn new processes from electron.
