### ISSUE TITLE
fs.readFileSync causes process termination

### ISSUE THREAD

**Issue by NikitaNO** [coreybutler/node-windows#116]
This line
```var config = JSON.parse(fs.readFileSync('./config.json'));```
causes
```Child process [2920 - C:\Program Files\nodejs\node.exe --harmony "C:\hello_world\node_modules\node-windows\lib\wrapper.js" -f "C:\hello_world\test.js" -l "Hello" -g 0.5 -w 2 -m 5 -r 3 -a n] terminated with 0```
Without it everything is fine

**Comment by gdexter** [comment]
If your config.json file is valid, just use:
var config = require("./config.json");

**Comment by coreybutler** [comment]
This isn't a node-windows issue so I'm closing it.

That said, I agree with @gdexter. That's the best approach. Alternatively, you may want to try

 `var config = JSON.parse(fs.readFileSync('./config.json').toString())`
