### ISSUE TITLE
Should it work on Windows 10?

### ISSUE THREAD

**Issue by GiovanniL19** [coreybutler/node-windows#118]
Hi,

I am running Windows 10 and have set everything up correctly (followed the guide). But nothing shows in the service list. When the run the node app.js the windows administrator access window pops up, I click yes then that's it. Nothing. Anyone got any ideas?

The following code is at the top of my app.js file:

```
var Service     = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'App Listener',
  description: 'Local server that listens for changes in the App.',
  script: 'C:\\NodeApps\\app-listener\\app.js' 
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});

svc.install();

```
Thank you in advance!

**Comment by GiovanniL19** [comment]
Answer is **Yes**, It does work with Windows 10. 
The issue I was having seemed to be linked with the name including the word 'Listener'. Not sure why.

**Comment by coreybutler** [comment]
Which version of node were you running? The `name` attribute is set using `process.title = name`. Older versions of node have a problem with this.... but it has been fixed in node for almost 2yrs now.
