### ISSUE TITLE
Node process is not terminated on service stop

### ISSUE THREAD

**Issue by ruimgoncalves** [coreybutler/node-windows#12]
When the service is stopped the wrapper process is detached and keeps running.
In my case the wrapper process spawns 2 child processes one node and one mongodb.
I have to terminate the process manually to restart the service.

I'm running windows 7 32 bits.

**Comment by codecounselor** [comment]
I ran into the same problem on node 6.9.4

My process tree looks like this at any given point in time, where the `electron.exe` is spawned from the script passed to `node-window`.
![image](https://user-images.githubusercontent.com/12678528/35532693-15a1d0e4-0509-11e8-9412-822ffb4fe1aa.png)

Initially I tried to kill the `electron.exe` process by listening to `svc.on('stop'...)` and killing my spawned process by it's pid.  That worked unless that process spawned children of it's own.  Even though they had then self-terminated for some reason the process tree would still remain after I stopped the windows service.

I've seen folks recommend adding the `stopparentfirst: true` option for other scenarios, and was pleasantly surprised to find that this addresses my problem.
It takes a while to stop the service, but I can deal with that.
