### ISSUE TITLE
after restart services needs to manually start

### ISSUE THREAD

**Issue by ezekel** [coreybutler/node-windows#120]
Hi Install node-windows in windows 10,  I followed your example in your documentation.
like this

```
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
    name:'MyApp',
    description: 'The service.',
    script: 'C:\\wamp\\www\\project\\myapp.js'
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
    svc.start();
});

svc.install();


```

but when I restart my laptop, and I go to services.msc the service installed is not running I need to manually start the service. How can I start this automatically ? the option is already set to automatically.

Thank you in avdvance.

**Comment by coreybutler** [comment]
What shows up in your logs?

**Comment by ezekel** [comment]
@coreybutler ,

where I can find the log ?

**Comment by coreybutler** [comment]
It should be in the [Event Log](https://github.com/coreybutler/node-windows#event-logging).

**Comment by ezekel** [comment]
@coreybutler ,

I will add this code to my code above ?

```
var EventLogger = require('node-windows').EventLogger;

var log = new EventLogger('Hello World');

log.info('Basic information.');
log.warn('Watch out!');
log.error('Something went wrong.');

```

**Comment by ezekel** [comment]
@coreybutler ,

How to use your EventLogger I just append the example logger to my service and also where I could find the GUI for the event Viewer in your documentation there is no steps on how to view the event viewer.

Thank you in advance.

**Comment by ezekel** [comment]
@coreybutler ,

here is the error in event viewer
```
The appsocket.exe service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```
```
A timeout was reached (30000 milliseconds) while waiting for the appsocket.exe service to connect.
```

**Comment by ezekel** [comment]
I fixed it just add wait time

**Comment by coreybutler** [comment]
Glad you got it fixed!
