### ISSUE TITLE
 I can not write to a file

### ISSUE THREAD

**Issue by afvsformatos** [coreybutler/node-windows#126]
I can not write to a file I made the step ponele an account and password to create as service and even the service itself windoe I have given user permissions but does not allow me anything to write to a file miestras q when you normally run npm start with let me write that same file with the same permission I need your help please

**Comment by coreybutler** [comment]
Please use [Gitter](https://gitter.im/coreybutler/node-windows) for future questions.

Check your filepath to make sure you're writing to an absolute path (not a relative path). I (or other community members) can probably help you more on Gitter.

**Comment by afvsformatos** [comment]
thanks
