### ISSUE TITLE
bundling with webpack 

### ISSUE THREAD

**Issue by omerts** [coreybutler/node-windows#129]
Hello,

When bundling this lib with webpack, I am getting errors because it loads the wrapper.js i a non-formal way, and wrapper.js is referencing optimist lib. Because of the way wrapper.js is used, webpack doesn't recognize it, or any of its dependencies, and doesn't insert them into the bundle.

**Comment by coreybutler** [comment]
Sounds like a webpack issue... I'm not sure I'd advocate bundling this with webpack in the first place. Daemons/background processes are not a part of an app.... they're used to run the app.
