### ISSUE TITLE
Script running as service or in console

### ISSUE THREAD

**Issue by michaelbaisch** [coreybutler/node-windows#130]
Just a quick question: Can I find out if a script runs as a service or in a console.

My script uses `readline` for debugging purposes, if that runs as a service the service exits immediately. So I would like to check if it runs as a service or in a console and depending on that, start `readline` or not.

**Comment by jazzdev** [comment]
I added an environment variable so my code can tell if it's running as a service.
```
var svc = new Service({
...
  env: [{
    name: "HOME",
    value: process.env["USERPROFILE"] // service is now able to access the user who created its' home directory
  },
  {
    name: "IS_SERVICE",
    value: "true" // so the code can tell if it's running as a service
  }]
```
Then check with `if (process.env.IS_SERVICE == 'true')`

**Comment by coreybutler** [comment]
@michaelbaisch - there isn't anything in the code to detect this, but @jazzdev's solution is a good one.

One way node-windows could support this would be to define an environment variable and apply it in the wrapper.js file. In other words, do what @jazzdev is doing, but automatically. I don't have time to do this, but if someone submitted a tested PR with this functionality, I would merge it.

**Comment by michaelbaisch** [comment]
Thanks for the input!
