### ISSUE TITLE
error creating service

### ISSUE THREAD

**Issue by roggaioso** [coreybutler/node-windows#135]
I installed the node-windows, I did the script to create a service, but the service wasn't created. In prompt, I ran the .exe generated in daemon folder, and received the following error:
` System.ArgumentNullException : Value can not be null Parameter name: . Path1 `

This is my script:
`var Service = require('node-windows').Service;`
`var svc = new Service({
  name:'bdogo-api',
  description: '..........',
  script: 'E:\\apps\\js\\bdogo-api\\app.js',
  wait: 2,
  grow: .5,
  maxRetries: 3,
  maxRestarts: 5
});`
`svc.on('install',function(){
  svc.start();
});`
`svc.install();`

So, I tried to unnistall the service, and received the following message :
`Fs.js : 1089
 return binding.unlink ( pathModule._makeLong (path ) ) ;`

`Error : EPERM : operation not permitted , unlink 'E:\apps\js\bdogo-api\daemon\bdogoapi.exe ' . `
Can you help me?

**Comment by roggaioso** [comment]
My server is a Win2012 . I hit the permissions on the folder application and created the service. Thank you!

But how do I access the application? My application provides some webservices, and running directly by npm, I had only access the URI

`http://172.31.15.160:3000/lotacoes/uorg`

I got the return. After creating the service, returns that I couldn't get an answer. With the running service, how should I call it ?

**Comment by roggaioso** [comment]
If I call `http://172.31.15.160/lotacoes/uorg` (without the port)

I get a 404 error .

**Comment by coreybutler** [comment]
Accessing your app via a URL has entirely to do with the underlying application, not with node-windows. There are a ton of reasons why this could be happening, so I'd recommend adding some logging to see when the server starts up (remember, you can write directly to the event log). 

Perhaps you have multiple web servers running on this machine? When you execute a request without the port, perhaps it's using another web server? If you're trying to run the node-windows version and the original version at the same time, there would be a port conflict on port `3000`. These are just guesses... it's kind of hard to tell without the application source code.

Detecting a port conflict is actually really easy now. I just released [porthog](https://github.com/coreybutler/porthog). Porthog identifies exactly which process is running on a port (or indicates nothing, if nothing is using the port).

**Comment by roggaioso** [comment]
This is my first node application. I used the Express to generate the initial code and made some adjustments. It seeks values ​​in a MongoDB and displays them as webservices.

app.js (node-windows service start this file)
[app.js.txt](https://github.com/coreybutler/node-windows/files/482385/app.js.txt)
agencias.js (one of the routes)
[agencias.js.txt](https://github.com/coreybutler/node-windows/files/482388/agencias.js.txt)
agencia.js (one of the shemas)
[agencia.js.txt](https://github.com/coreybutler/node-windows/files/482397/agencia.js.txt)


There is an Apache running on this machine. As I would call forwarding for this application being executed by the service created with node-windows, since they do not know which port it is running ?

**Comment by coreybutler** [comment]
The key line I was looking for (that I didn't find) in the code was a `app.listen()` call (or a variation of that). In Express (and node's native http), this is the method where you specify the port and launch the server. You don't want to use both Apache and Express for the same purpose. Express is a web server, so you don't need Apache for that. People that use Apache/NGINX/etc with Express are typically using Apache for virtual hosting/routing/proxying... not web serving.

Seeing as this is your first Node app, you may benefit from an example a friend and I put together for our meetup. Be aware that it's nearly 2yrs old, but still relevant. The code is available in a repo called [groops](https://github.com/groops). The node code that might help you is in the [node-express](https://github.com/groops/examples/tree/master/backend/node-express) directory. I don't know if the database is still active, but the code shows how to use Express and connect to Mongo (it doesn't use Mongoose, but the principles are the same). There is a [video of the meetup](https://www.youtube.com/watch?v=LYUhwxomR4k) where we discuss how/why this app was built, starting around 32 minutes and 45 seconds into the video (Brian does most of the walkthru, I answer a couple of questions throughout).

**Comment by roggaioso** [comment]
Just to be clear, this machine already was running Apache to serve my intranet. My idea is to create node applications, and from the intranet, create links to access these applications. So I need both the Apache and Node.js running. Thinking that later I would have several node applications, it sparked my interest in node-windows.

**Comment by roggaioso** [comment]
It worked! Just following his commentary about `listen` , I added the following code in app.js :

```
app.listen ( 3000, function () {
  console.log ( ' app listening on port 3000 !');
});
```
and I started the service created with node-windows ..... success!
Now I can create my applications on the intranet and linking to node applications.

Thank you!
