### ISSUE TITLE
using a service as a chrome native messaging host?

### ISSUE THREAD

**Issue by wkentdag** [coreybutler/node-windows#136]
Hi - first I just want to say thanks for developing this awesome package. I see that there's already a handful of open issues and that you're looking for maintenance help, so I'll keep my question brief:

As I mentioned in https://github.com/jdiamond/chrome-native-messaging/issues/5, I'm trying to use this package to create a windows service that acts as a host for a chrome extension using [native messaging](https://developer.chrome.com/extensions/nativeMessaging). When I try to "connect" to the host from my extension, I get a windows permission warning about the executable:

```
"do you want to allow this app from an uknown publisher to make changes to your device?" 

<my_service_executable.exe>  

Program location: "C:\Users\me\code\chrome-native-messaging\daemon\my_service_executable.exe --parent-window=3998946 chrome-extension://<id>/`
```

When I approve the permissions, the service disconnects from the app.
I got similar warnings when building the service in a regular command prompt, but these disappeared once I started running it in a prompt with elevated admin privileges. However, the warnings persist when I try to connect the extension to the service/host no matter what. This is my first time developing something for Windows, so I'm just wondering if anybody has insights into how to silence these warnings, or maybe if somebody has successfully used a `node-windows` service as a native messaging host. Thanks!

**Comment by coreybutler** [comment]
I haven't done specifically what you're doing, but I don't think this is specific to Windows... sounds like your hangup is the Chrome permissions. Chrome, and any extensions, are still subject to the security requirements of the browser... there's nothing node-windows can do for that.

Perhaps something like [electron](https://electron.atom.io) would be a better fit than node-windows. It has a number of Chrome permissions enabled by default. I can't say with certainty that it would behave exactly as you're expecting, but perhaps it could point you in the right direction.

Another potential solution might be [node-notifier](https://github.com/mikaelbr/node-notifier).

**Comment by wkentdag** [comment]
Thanks for the suggestions @coreybutler. We're already using electron for another component of this project so I was thinking of moving in that direction too. Going to close this out but I'll comment here if I do find a solution. Thanks!
