### ISSUE TITLE
Child process [...  -g 0.25 -w 1 -r 3 -a n] terminated with 0

### ISSUE THREAD

**Issue by dev-sergey-mishin** [coreybutler/node-windows#139]
Hello, when I run the server and turn on the url, the service stops with the log:

Child process [19932 - C:\Program Files\nodejs\node.exe --harmony "C:\Users\user\AppData\Roaming\npm\node_modules\node-windows\lib\wrapper.js" -f "C:\IDEV\Project\Web\keystone.js" -l "ProjectName" -g 0.25 -w 1 -r 3 -a n] terminated with 0

service runner code:

```
var Service = require('node-windows').Service;

var svc = new Service({
  name:'ProjectName',
  description: 'some desc',
  script: 'C:\\Project\\Web\\keystone.js'
});
 
svc.on('install',function(){
  svc.start();
  console.log('install complete');
  console.log('The service exists: ' ,svc.exists);
});
 
svc.install();
```

nodejs server code:

```
require('dotenv').config();
var keystone = require('keystone');

keystone.init({
	'name': 'ProjName',
	'brand': 'ProjName',
	'less': 'public',
	'static': 'public',
	'favicon': 'public/favicon.ico',
	'views': 'templates/views',
	'view engine': 'jade',
	'auto update': true,
	'session': true,
	'auth': true,
	'user model': 'User',
});
keystone.import('models');
keystone.set('locals', {
	_: require('lodash'),
	env: keystone.get('env'),
	utils: keystone.utils,
	editable: keystone.content.editable,
});
keystone.set('routes', require('./routes'));
keystone.set('nav', {
	posts: ['posts', 'post-categories'],
	users: 'users',
});

keystone.start();
```

**Comment by Gadenm** [comment]
try to run this command on CMD , it will throw meaningful error.

**Comment by asuciu** [comment]
I moved an app from using http to https and I am getting the same exact problem. I ran the command in CMD and the app starts just fine. Whenever I start the application from the Services window it shuts down immediately with the above-mentioned error. Any ideas?

Thanks.

**Comment by coreybutler** [comment]
Since @asuciu seems to have found the solution (and since the OP hasn't responded), I'm closing this. For any future seekers, make sure you check out the [wiki](https://github.com/coreybutler/node-windows/wiki) if you're experiencing similar problems.
