### ISSUE TITLE
specify services dependencies

### ISSUE THREAD

**Issue by dariosalviwork** [coreybutler/node-windows#151]
Hi,

I would like to be able to specify dependencies for my service. This will allow Windows, for example, to start a database first and my own nodejs service later.
I can't find any way to do it with this module.

**Comment by coreybutler** [comment]
Closing due to extreme age. 

For all you Googlers landing on this, [shortbus](https://github.com/coreybutler/shortbus) is a good tool for sequencing. It could be used to start other processes before executing anything else.
