### ISSUE TITLE
xml@0.0.12 is required by node-windows@0.1.13

### ISSUE THREAD

**Issue by jlouzil** [coreybutler/node-windows#161]
Hello, I'm absolutely novice - maybe missed something, just I'm having troubles how to get out-of-dated xml@0.0.12 because only the latest/stable ver 1.0.1 looks to be available for public download. Not sure you can update your code to require xml/1.0.1 or can you please suggest something. Thanks!

**Comment by coreybutler** [comment]
NPM maintains all versions of each module, so a simple `npm install node-windows` should still work.

**Comment by jlouzil** [comment]
stupid, thanks. I found that npm install is often suggested method how to get module, just did not know it manages req. versions. thanks again
