### ISSUE TITLE
how we can write node js server logs into a file if using node-windows

### ISSUE THREAD

**Issue by anandgupta193** [coreybutler/node-windows#168]
@coreybutler id there any provision that we can write node server logs into a file if we ran our node server as windows service using node-windows?

**Comment by coreybutler** [comment]
There's nothing stopping you from writing your own log files to disk, if that's what you're asking. Just make sure you are storing the log file in a directory the app has permissions to write to.

If you want to write to the Windows event logs, node-windows [supports that](https://github.com/coreybutler/node-windows#event-logging).
