### ISSUE TITLE
run as service binary application instead of node.js script

### ISSUE THREAD

**Issue by Tunga37** [coreybutler/node-windows#169]
Is there a possibility to use this module to run binary's application as service instead of node.js script?

I would expect something like this
```var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  path_to_bin: 'C:\\path\\to\\myapp.exe'
});

Is there a way to achieve that?

**Comment by coreybutler** [comment]
That would defeat the purpose of this module.  If you need to run a binary from node, just use node's [built in child process](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html).
