### ISSUE TITLE
Start exe without node

### ISSUE THREAD

**Issue by furyscript** [coreybutler/node-windows#170]
Hi,

Can we start generated `.exe` on another pc that haven't `node` installed??
We try a lot but unfortunately without success.

**Comment by coreybutler** [comment]
No. Tools like Electron, NW.js, and Nexe are better for shipping a binary.

**Comment by coreybutler** [comment]
Added a [wiki entry](https://github.com/coreybutler/node-windows/wiki#can-a-exe-created-with-node-windows-run-on-a-computer-without-nodejs-installed) for this.
