### ISSUE TITLE
Is it possible to pass parameters to the script ?

### ISSUE THREAD

**Issue by paulpeeters** [coreybutler/node-windows#182]
How can I pass parameters  to the script to be run as a Windows service ?

var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\path\\to\\helloworld.js',
  params: '--port 8010 --log "C:\\path\\to\\helloworld.log" '
});

**Comment by coreybutler** [comment]
Command line arguments aren't _directly_ supported, since a wrapper is required. However; there are a few ways to accomplish this.

I'd suggest using [environment variables](https://github.com/coreybutler/node-windows#environment-variables) instead.

**Comment by mojoaxel** [comment]
A `scriptOptions` was added with #190
