### ISSUE TITLE
How to enable ES6

### ISSUE THREAD

**Issue by electrozed** [coreybutler/node-windows#183]
i am enable to install and start the service but my node file is writing in ES6

there is any option to run it with ES6 ?

thank you

**Comment by coreybutler** [comment]
This doesn't actually have anything to do with node-windows. As long as you're running a version of Node that supports ES6, then it should just work.

**Comment by electrozed** [comment]
its not very currecr because 
to run node js with es6 i am using this command : 
babel-node --preset babel-preset-es2015 example.js 
so i cannot use it with the node-windows

**Comment by coreybutler** [comment]
Babel is for frontend code.... there is no need to use it on the backend. The `babel-noed --preset babel-preset-es2015` part is completely unnecessary.

You may be better off posting a question on StackOverflow. Remember to describe what you're trying to do and provide code examples.
