### ISSUE TITLE
Disable event logging

### ISSUE THREAD

**Issue by HekMe** [coreybutler/node-windows#186]
Any way to disable event logging?

Thanks

**Comment by 543802360** [comment]
I have the same question

**Comment by hektor157** [comment]
I see that there's new update, but without this option. Will it be implemented?
Thanks

**Comment by jdziat** [comment]
Can you give me some more specifics around this? I’m not sure why you would want to disable this when you can just choose to ignore it.

**Comment by HekMe** [comment]
We don't need it, cause we have our own logging solutions. 
So it's just wasting space on our clients, endpoints and our distributed backup network.
And we'd like to have silent installation/life of our apps.

**Comment by rhartvig** [comment]
exact same situation as @HekMe - did we get a way to disable it?

**Comment by rhartvig** [comment]
Found a way to do this, in case others need it:

```
svc = new Service({
  ...
  logging: {
    mode: 'none'
  }
})
```
Remember to reinstall. For details see node_modules/node-windows/lib/winsw.js
