### ISSUE TITLE
A naive question, why doesn't `opn` work in node-windows but from command line?

### ISSUE THREAD

**Issue by foresightyj** [coreybutler/node-windows#187]
From my observation, it is not just `opn` but anything that involves user interactions. These commands will not have any effect when called from a service installed via node-windows but works perfectly fine when run in command line.

I tried the following so far:
1. In services, right click the installed service and choose property. Click on Logon tab and ensure `Local System account` is ticked and then tick `Allow service to interact with desktop`. **Doesn't work**.
2. In the same tab as above, switch to administrator account. **Still doesn't work**.

Does windows impose restrictions for services which I am not aware of?

**Comment by coreybutler** [comment]
Closing due to age.
