### ISSUE TITLE
User domain/user/password question

### ISSUE THREAD

**Issue by yosiasz** [coreybutler/node-windows#188]
Greetings,

Great tool! When creating a service and specifying domain, username and password, is this the user name used in the Logon tab of the service property?
Because if it is, it is not sticking, it just shows, local System account enabled.

Thanks!

**Comment by coreybutler** [comment]
In most cases, yes, it should be what's used in the login tab. Keep in mind it needs to be an actual user, either registered with the machine or Active Directory. If it can't find the user, it would fall back to the local system account.

**Comment by click2install** [comment]
NT AUTHORITY\LOCAL SERVICE is not working, the output is as described above where it appears to fallback to the NTA\SYSTEM account.

Specifying `svc.user.account = 'LOCAL SERVICE'` also has the same effect.

![image](https://user-images.githubusercontent.com/6037592/32423252-6c7c0544-c2f9-11e7-8fb9-ed4d4a9c56ee.png)

![image](https://user-images.githubusercontent.com/6037592/32423273-93fee1ea-c2f9-11e7-938c-cb6c7600d398.png)

**Comment by Flonk** [comment]
I'm running into similar problems, though it's entirely possible it's me being stupid. I've tried

```
service.user.domain = "domain";
service.user.account = "samaccountname";
service.user.password = "password";
```

as well as

```
service.user.domain = "domain";
service.user.account = "samaccountname@domain";
service.user.password = "password";
```

as well as

```
service.user.account = "domain/samaccountname";
service.user.password = "password";
```

as well as a local account, all to no avail. I am running the script from an administrative command prompt with domain admin permissions (win8.1).

**Comment by nick-beers** [comment]
Just in case anyone else is running into this issue I wanted to update this with the solution. I dove into the source code and found that instead of using the documentation base solution:
```
svc.user.domain = 'mydomain.local';
svc.user.account = 'username';
svc.user.password = 'password';
```
you'll need to use the following: 
```
svc.logOnAs.domain = 'mydomain.local';
svc.logOnAs.account = 'username';
svc.logOnAs.password = 'password';
```
I think the documentation should be updated to correct the instructions. @coreybutler

**Comment by jdziat** [comment]
Thanks for bringing this up @nick-beers. This should be consistent across all node-{os} packages.
