### ISSUE TITLE
Service not auto started after rebooting system 

### ISSUE THREAD

**Issue by ashwinijindal10** [coreybutler/node-windows#193]
i am facing the issue after installing service , which run my node program  using node-windows package, it creates a service successfully  with automatic start up mode but when i restart my system to verify service auto start mode, it does not get started automatically , when i look at the event viewer logs , it shows service manager has tried to re start the service after system reboot , but it failed to do that due to "The service did not respond to the start or control request in a timely fashion." and another one "A timeout was reached (30000 milliseconds) while waiting for the Hello.exe service to connect." but when i try to start that service manually, it works very well. It is hard to figure out  why service get failed when system try to start it after reboot.

**Comment by ashwinijindal10** [comment]
i solved this problem , by updating the file "winsw.js","daemon" inside of node-window package .As attached images to configure my service dependent on Eventlog,W32Time services . 

![image](https://user-images.githubusercontent.com/1833607/33875173-6a8a2abc-df47-11e7-9932-c748d1a2baca.png)
![image](https://user-images.githubusercontent.com/1833607/33875206-887a10be-df47-11e7-93d5-560191a85754.png)

**Comment by nicoabie** [comment]
@ashwinijindal10 Care to provide a pull-request with the changes so it is easier to see the diffs?

**Comment by coreybutler** [comment]
Closing due to age. I'd love to see a PR of this too.

**Comment by Kriess2507** [comment]
> i am facing the issue after installing service , which run my node program using node-windows package, it creates a service successfully with automatic start up mode but when i restart my system to verify service auto start mode, it does not get started automatically , when i look at the event viewer logs , it shows service manager has tried to re start the service after system reboot , but it failed to do that due to "The service did not respond to the start or control request in a timely fashion." and another one "A timeout was reached (30000 milliseconds) while waiting for the Hello.exe service to connect." but when i try to start that service manually, it works very well. It is hard to figure out why service get failed when system try to start it after reboot.

@ashwinijindal10 what configurations did you do to start your services automatically?
