### ISSUE TITLE
Possible to use events for already existing services?

### ISSUE THREAD

**Issue by mpathy** [coreybutler/node-windows#194]
I use node-windows, node-linux, node-osx for installing new services and control them, but I also would like to monitor already existing services for a monitoring tool.

Is it possible to use the nice event emitters of those three plugins to "monitor" existing services?

**Comment by coreybutler** [comment]
At the moment, there's no easy way to tap into an existing service. Handling events depends on an accessible wrapper, which is how the install process is able to handle events.

I like this concept and I'd be open to a PR across all three modules if someone wants to implement it.
