### ISSUE TITLE
Chinese support for 'list' function

### ISSUE THREAD

**Issue by zhanghuanchong** [coreybutler/node-windows#196]
Now it will get mess code on Windows with Chinese as default language when executing `list` function.

Need to change page code to 437 to get output in English before running `tasklist` command, like this:
```
chcp 437 && tasklist ...
```

**Comment by coreybutler** [comment]
PR welcome.

**Comment by jdziat** [comment]
This is a request for functionality and can be closed. Once a PR is submitted we can review and go from there.
