### ISSUE TITLE
Feature: set ID and PID option

### ISSUE THREAD

**Issue by oliveirag** [coreybutler/node-windows#199]
```
 var svc = new Service({
   pid: 88888,
   name:'Hello World',
   description: 'The nodejs.org example web server.',
   script: 'C:\\path\\to\\helloworld.js')
 });

```
It would be useful for killing the process.
Setting the id of the service instead of just calling it name.exe would also be good.

**Comment by coreybutler** [comment]
There is no way to set the PID using the underlying winsw library, so it's not possible to _set_ it. A feature to _retrieve_ the PID from the `install` event would be possible, but I'm not going to have time to add that anytime soon (PR welcome).

If your service happens to be using a port (i.e. a web/net server), another possible option would be [porthog](https://github.com/coreybutler/porthog). This will retrieve the PID for a process on any given port.
