### ISSUE TITLE
Network service dose not start in Program Files

### ISSUE THREAD

**Issue by reactionic127** [coreybutler/node-windows#201]
I implement a network service.
If I put the project in C:/ or D:/ the service works well.
But if I put the project in C:/program files or C:/windows, the service couldn't start.
Please help me.

**Comment by coreybutler** [comment]
`C:\Program Files` and `C:\windows` are protected directories. Windows requires the service to use an account with administrative privileges. My guess is the account running the service doesn't have proper permissions, which is why it works on other directories and not the two you mentioned.
