### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by borgold** [coreybutler/node-windows#203]
node-windows automatically inserts non-existent company (Sun Microsystems) copyright into registered service executable. And Jenkins owners as well: <Copyright 2008-2013 Sun Microsystems, Inc., CloudBees, Inc.>
How do I override this notice? Documentation looks super compacted, a lot of issues are not covered.

**Comment by coreybutler** [comment]
I believe these are copyrights from winsw, the underlying library that generates the XML/exe.
