### ISSUE TITLE
Question: How can I build the Windows Service exe?

### ISSUE THREAD

**Issue by sGambolati** [coreybutler/node-windows#205]
Hi!
I'm pretty new with this project. I wonder if is possible to run the a cmd to build the .exe in a CI build server. I know that running the .js will build and install the app, but as I want to build binaris without need of installing.

Thanks!

**Comment by coreybutler** [comment]
This project doesn't specifically generate binaries. You could cherry-pick the code for it, but you're likely better off directly using winsw if your goal is just to build the binary.

**Comment by jdziat** [comment]
I agree with @coreybutler  and don't think this is a relevant issue to pursue. If you need help generating a xml file to use with winsw there should be available libraries for that. 

Closing this as it's not pertinent to this project.

**Comment by sGambolati** [comment]
Ok. Thanks.
