### ISSUE TITLE
The service restart  unexpectedly

### ISSUE THREAD

**Issue by jugonzalez40** [coreybutler/node-windows#207]
Hi, I have a script which read a three xml (very heavy) files asynchronously and insert bulk from mssql asynchronously, I execute the script by console and the script runs fine, but in service it restarts at the second bulk, I belive this is caused for a limit configuration

**Comment by coreybutler** [comment]
I would check your limitations if that's what you think is causing it to restart. Also check the logs, which should provide more detail.
