### ISSUE TITLE
node window service not install in window 10

### ISSUE THREAD

**Issue by ghost** [coreybutler/node-windows#216]
C:\Users\tarun\Downloads\node-windows-master(1)>npm install node-windows
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\tarun\Downloads\node-windows-master(1)\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\tarun\Downloads\node-windows-master(1)\package.json'
npm WARN node-windows-master(1) No description
npm WARN node-windows-master(1) No repository field.
npm WARN node-windows-master(1) No README data
npm WARN node-windows-master(1) No license field.

+ node-windows@0.1.14
added 5 packages from 8 contributors and audited 5 packages in 6.15s
found 0 vulnerabilities

C:\Users\tarun\Downloads\node-windows-master(1)>npm link node-windows
C:\Users\tarun\Downloads\node-windows-master(1)\node_modules\node-windows -> C:\Users\tarun\AppData\Roaming\npm\node_modules\node-windows

C:\Users\tarun\Downloads\node-windows-master(1)>

every time i'm getting same response install node window services.
if any solution please tell me.

**Comment by coreybutler** [comment]
Something is going on with your configuration... are you using a version manager or are you behind a proxy?

**Comment by tarun920** [comment]
No i'm not using any version manager and also removed proxy but still same issue...

**Comment by AshishShanker** [comment]
Did you do an `npm init` in `node-windows-master` directory? Looks like npm can't find your project's `package.json`

**Comment by coreybutler** [comment]
@AshishShanker is correct... this looks like a missing package file.
