### ISSUE TITLE
Service doesn't restart after error

### ISSUE THREAD

**Issue by TimothyY** [coreybutler/node-windows#22]
I am using windows server 2012 and have successfully create and run the service.
When my node application exit with error (in this case,  database has query error), the *.err.log file correspond correctly, however the service doesn't restart itself. the service status is still running and it never stop.

I have edit my service properties like this:
----Recovery tab
-first failure, second failure, subsequent failure with restart the service 
-reset fail count after 1 day
-reset service after 1 minutes
-enable actions for stops with error.

----Log On tab
allow service to interact with desktop

I have also change the daemon/*.exe properties to run as administrator and checked the user privilege with isAdminUser() and it returns that the user has administrative privileges.

on the service object, i use this attributes :
wait: 1,
  grow: .25

is there something I miss ?

**Comment by rogierschouten** [comment]
Auto-restart is not working for me at all. Using a simple test script that only contains 
```javascript
throw new Error("test error")
```
The service will not restart at all. Is there any new release planned?

**Comment by coreybutler** [comment]
@rogierschouten - How did you configure the install? If it's configured to abort on error, then this is expected behavior. Which version of Windows?

**Comment by rogierschouten** [comment]
```javascript
	var svc = new Service({
	  name:'ExampleService',
	  description: 'My Example Service.',
	  script: path.join(__dirname, "exampleservice.js"),
	  wait: 2,
	  grow: 0.25,
	  maxRestarts: 5,
	  abortOnError: false
	});

	// Listen for the "install" event, which indicates the 
	// process is available as a service. 
	svc.on('install',function(){
	  svc.start();
	});
	 
	svc.install();
```

exampleservice.js:
```javascript
throw new Error("test error");
```

**Comment by rogierschouten** [comment]
And Windows 7

**Comment by coreybutler** [comment]
@rogierschouten - I think the issue is node-windows doesn't know where your script is. Using `_dirname` is relative pointer to the module directory, and since node-windows uses a wrapper, it would be looking for your script in the node-windows module directory. Try using an absolute path instead of referencing `__dirname`.

**Comment by rogierschouten** [comment]
Ah thanks that will be it.

**Comment by coreybutler** [comment]
For anyone reading this, there is now a wiki entry covering the [most common reasons](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why) for this behavior.
