### ISSUE TITLE
Functionalities are not working properly

### ISSUE THREAD

**Issue by upardhi** [coreybutler/node-windows#221]
Here are the steps I use to install services 
D:\colorization-demo>npm install -g node-windows
+ node-windows@0.1.14
added 5 packages in 1.094s

D:\colorization-demo>npm link node-windows
D:\colorization-demo\node_modules\node-windows -> C:\Users\tage_demo2\AppData\Roaming\npm\node_modules\node-windows

If I run same code using node index.js its working properly

**Comment by upardhi** [comment]
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'Colorization',
  description: 'TColorization',
  script: 'D:\\colorization-demo\\index.js',
  nodeOptions: [
    '--harmony',
    '--max_old_space_size=4096'
  ]
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});

svc.install();

**Comment by coreybutler** [comment]
Have you reviewed https://github.com/coreybutler/node-windows/wiki#frequently-asked-questions?

**Comment by upardhi** [comment]
Yes, I read this. I am trying to use "exec" to run the command of ImageMagick software. and it's not working.

**Comment by coreybutler** [comment]
Closing due to age.
