### ISSUE TITLE
Windows Script Host Error

### ISSUE THREAD

**Issue by jugonzalez40** [coreybutler/node-windows#224]
Hi, i'm trying to install a simple service, the code works fine in console, and Windows 10, but when I run the install script in production server (Windows Server 2017 || NodeJS 6.10.0 || node-windows ~0.1.14) throws me the next error 
![image](https://user-images.githubusercontent.com/36463583/48231725-27073100-e37d-11e8-82c9-924adc719748.png)

The user who is running the cmd has Admin role.

**Comment by coreybutler** [comment]
Should be easier to support elevation with the 1.0.0 release.
