### ISSUE TITLE
abortOnError checks for instanceof Boolean, so primitive `true` is interpreted as `false`

### ISSUE THREAD

**Issue by theredpea** [coreybutler/node-windows#229]
Not sure if intentional, may be "working as designed"
daemon.js `abortOnError` argument  checks for [instanceof Boolean](https://stackoverflow.com/q/203739/1175496), 

This means if I pass abortOnError : true (primitive `true`), the [daemon](https://github.com/coreybutler/node-windows/blob/master/lib/daemon.js#L211) will interpret and run with the argument `false`!

If it helps I can make pull request to do either of these:

1. Change the daemon.js line to stop using `instanceof`
  - to this: ` config.abortOnError === true ? config.abortOnError : false`
  - checking for == true is more consistent with the other line `(this.abortOnError==true?'y':'n'),`
2. Change the documentation to recommend a Boolean object instead of a Boolean primitive
  - so remove this:  
> an attribute called abortOnError can be set to true...
  - replace with this:  
> an attribute called abortOnError can be set to `new Boolean(true)`...

**Comment by coreybutler** [comment]
Yeah, that was a kludgy implementation. It's updated in master.
