### ISSUE TITLE
Just get a pid by application name.

### ISSUE THREAD

**Issue by TongDaDa** [coreybutler/node-windows#230]
I Want to find a pid by targeted application name, however, this package not have now.

Its `list` method is get all the services on the computer, so I want to get some pid by a name of `EXE`

How do I do to?

**Comment by TongDaDa** [comment]
In addition, my list of services is messy code.. 

If this situation is caused by certain computer so that it wound't use stably.

**Comment by coreybutler** [comment]
Just [filter the array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) so it only returns what you want.
