### ISSUE TITLE
Using  node-windows in electron app

### ISSUE THREAD

**Issue by Firlfire** [coreybutler/node-windows#232]
Hi,

I have an issue using node-windows in my electron app. I already check this post but it did not help me
[https://github.com/coreybutler/node-windows/issues/173](url)

My project is almost the same : The Electron app will just allow me to "manage" the service via a Tray Menu and especially to install it with a multi-platform setup (.exe, .msi, linux, ...).

My problem : the whole app works in dev (Tray menu, install service, start/stop service and others features via the menu). Electron can build it (.exe). It installs the app but when it starts an error message is displayed : "Cannot find module 'node-windows'" (see screenshot for more details)

I have two package.json and both contain "node-windows": "^0.1.14" in dependencies
-root/
--app/
---package.json
--package.json ("main": "app/electron.js")

Can you help me please ? You can find my electron.js file and how it use the service in service.js (attached as .txt files)

![node-windows](https://user-images.githubusercontent.com/28627488/53583775-884c4d80-3b82-11e9-8cf3-751cd3645a12.PNG)
)
[electron.txt](https://github.com/coreybutler/node-windows/files/2916086/electron.txt)
[service.txt](https://github.com/coreybutler/node-windows/files/2916087/service.txt)

**Comment by coreybutler** [comment]
Closing due to age. 

For anyone coming across this via a Google search:

This most likely has to do with the build process not properly including node-windows. Issue #245 dives into some detail about working with Electron and node-windows
