### ISSUE TITLE
maxRestarts cannot be set to zero

### ISSUE THREAD

**Issue by dsbert** [coreybutler/node-windows#233]
The truthy check prevents setting maxRestarts to zero.

https://github.com/coreybutler/node-windows/blob/bf0cf090f3bbcb1f56d8e1672d764b15aadd30f9/lib/daemon.js#L194-L198

**Comment by dustingraham** [comment]
Would `abortOnError: true,` suffice? What's the purpose of setting it to zero?

**Comment by dsbert** [comment]
@dustingraham 

The following can be found in the source documentation.

```
    /**
     * @cfg {Number} [maxRestarts=3]
     * The maximum number of restarts within a 60 second period before haulting the process.
     * This cannot be _disabled_, but it can be rendered ineffective by setting a value of `0`.
     */
```

Does the documentation specify how this setting is used (or not used) if `abortOnError` is set to `true`? Right now, it will always be sent as a command line argument to the `.exe`

**Comment by coreybutler** [comment]
I think this is a bug. Line 198 should really be 

```javascript
value: config.hasOwnProperty('maxRestarts') ? config.maxRestarts : 3
```
