### ISSUE TITLE
node-windows in electron production problem

### ISSUE THREAD

**Issue by emirgokdas** [coreybutler/node-windows#238]
I have created a project that listen 514 port and save syslog messages. It's need to run server.js as a windows service to run forever. I use node-windows with electron. Everything is run well in development , installing service, start, restart etc. Hovewer in production. It just install service, when i look at the deamon folder, err.log and out.log files is empty, service run in that time. How can solve this issue

**Comment by coreybutler** [comment]
Please see https://github.com/coreybutler/node-windows/wiki.
