### ISSUE TITLE
Launching gulp task as a service ?

### ISSUE THREAD

**Issue by orty** [coreybutler/node-windows#242]
Hi,

I am looking for a way to use this library to run a specific gulp task as a Windows service. I already created multiple plain nodejs services but I cannot find a way to execute gulp instead.

Thank you

**Comment by coreybutler** [comment]
This would be a gulp issue if you're using the gulp API. If you're trying to use it as a CLI utility, then you need to install it and reference it (likely with a `child_process.exec`) using a relative path to the node module. See the comment on #244, which is trying to do the same thing with grunt.
