### ISSUE TITLE
new release and missing tagged releases on GitHub

### ISSUE THREAD

**Issue by DanielRuf** [coreybutler/node-windows#248]
There were new changes after 2017-02-21

https://github.com/coreybutler/node-windows/compare/0.1.11...master

And it seems the tags were not pushed to GitHub:
https://github.com/coreybutler/node-windows/releases

Would be great to have them here too.

**Comment by coreybutler** [comment]
I don't really maintain this much anymore (no time).... but I just went through and merged a bunch of PR's and automated the release process, which includes tags/releases (plus the obvious npm release).
