### ISSUE TITLE
future maintenance

### ISSUE THREAD

**Issue by DanielRuf** [coreybutler/node-windows#249]
I saw that you are looking for new maintainers:

https://github.com/coreybutler/node-windows/compare/1.0.0-beta.1...master

I would be interested to help with that.

**Comment by coreybutler** [comment]
Let's connect & discuss. I'd prefer to keep Github issues focused on bugs... I tried to send you a LinkedIn invite but don't know your email address.... can you send me a LinkedIn invite (https://www.linkedin.com/in/coreyabutler)?
