### ISSUE TITLE
Error on wincmd.kill - Process can only be terminated forcefully (with /F option).

### ISSUE THREAD

**Issue by de-mim-1974** [coreybutler/node-windows#250]
I like your package, thank you for that! 

If I execute the following on node-windows@1.0.0-beta.1
```javascript
wincmd.kill(11624, function (msg) {
   console.log('result: ' + msg)
});
```
I get the following output:
> result: Error: Command failed: taskkill /PID 11624
> ERROR: The process with PID 11624 could not be terminated.
> Reason: This process can only be terminated forcefully (with /F option).

Is there a way to execute the command with the /F option?

**Comment by coreybutler** [comment]
Thanks, I'm glad the module is proving useful for you.

To answer your question, yes, the `kill` command has an optional boolean attribute:

```javascript
wincmd.kill(11624, true, function (msg) {
   console.log('result: ' + msg)
})
```

See https://github.com/coreybutler/node-windows/blob/master/lib/cmd.js#L28-L38 for the implementation.
