### ISSUE TITLE
Script doesn't start

### ISSUE THREAD

**Issue by lekhmanrus** [coreybutler/node-windows#252]
The issue I'm facing with, script is not starting at all. I've even tried [example from this repo](https://github.com/coreybutler/node-windows/tree/master/example). I've tried to run it **with** and without Administrator rights.

Windows Events Log:
![image](https://user-images.githubusercontent.com/2744696/75376856-fb6bcb00-588d-11ea-875c-ae7c03e3c667.png)
`Child process [22276 - C:\Program Files\nodejs\node.exe  --harmony C:\github\node-windows\lib\wrapper.js --file C:\github\node-windows\example\helloworld.js --scriptoptions= --log "Hello World wrapper" --grow 0.25 --wait 1 --maxrestarts 3 --abortonerror n --stopparentfirst undefined] finished with -1073741502`

```sh
node -v
v13.9.0
```

**Comment by coreybutler** [comment]
Have you checked https://github.com/coreybutler/node-windows/wiki#my-script-installs-but-wont-start-with-no-error?

Also, I wonder how your install code looks, mostly because of this: `--stopparentfirst undefined`.

**Comment by lekhmanrus** [comment]
Hi @coreybutler ,

Yes, I've checked Wiki.

Steps to reproduce:
1. `git clone https://github.com/coreybutler/node-windows.git`
2. `cd node-windows && npm i`
3. Change path at `example/install.js`
![image](https://user-images.githubusercontent.com/2744696/75379792-33294180-5893-11ea-9b8d-eec59713219a.png)
4. `node .\example\install.js`
5. I have that warning at Windows Event Log and it seems like `helloworld.js` is not triggering at all.

**Comment by lekhmanrus** [comment]
@coreybutler,
I'm sorry. I've restarted my machine and tried it again - it works now.
I have no idea what was the issue.
Sorry for wasting your time.
