### ISSUE TITLE
Allow package to be installed on Linux

### ISSUE THREAD

**Issue by forty** [coreybutler/node-windows#264]
Hello, I'm trying to use this package by bundling it with my application. Unfortunately my build/packaging is done on Linux so `npm install node-windows` fail because of the `os` property in the package.json

Would it be possible to remove the OS property so this package can be installed on Linux too?

Thanks

**Comment by coreybutler** [comment]
I've gone back and forth on this over the years. 

There are a number of use cases where people are using node-mac/linux as well to create universal installers, so they're depending on this feature to prevent installation of the other packages. However; the last time I thought about this was when  `peerDependencies` were automatically installed. It does make sense to remove the OS restriction, as long as users of the noted use case are willing to leverage peerDependencies (which seems reasonable to me).

I'm going to do this. If anyone comes across this issue in the future, open a new issue referencing this one.

**Comment by forty** [comment]
Awesome! Thanks a lot!
