### ISSUE TITLE
Issue with running node-windows script from Innosetup

### ISSUE THREAD

**Issue by bitshiftnetau** [coreybutler/node-windows#265]
Having issues running node-windows script from innosetup. Have tried using both Filename execute and pascalScript methods. 

See stack thread here: [Issue with installing node application as a service using innosetup and node-windows as a script](https://stackoverflow.com/q/63009117/9479013)

**Comment by coreybutler** [comment]
This is kind of tough to troubleshoot, but I suspect the InnoSetup process may be creating an orphan directory. 

From what I can tell in the line below, the current working directory is relative to the InnoSetup process:

`Filename: "{pf64}\nodejs\node.exe"; Parameters: "{app}\validation-installer-node-windows.js";`

If memory serves, this defaults to a temporary directory.  This would explain why it works partially with InnoSetup and completely without it.

I'd recommend explicitly defining the current working directory to assure this line is writing the output to the appropriate directory. I can't remember exactly how that's done with InnoSetup off the top of my head, but I remember dealing with something similar in the [NVM for Windows install script](https://github.com/coreybutler/nvm-windows/blob/master/nvm.iss).

**Comment by bitshiftnetau** [comment]
Ok cool. That makes sense. 

Do you mean the {app} variable?

**Comment by bitshiftnetau** [comment]
Ok so you were correct. I did not set the WorkingDir parameter, nor was I passing in the correct parameters to ShellExec.

**Comment by coreybutler** [comment]
Glad you got it figured out @bitshiftnetau, happy coding!
