### ISSUE TITLE
Vulnerability in Minimist

### ISSUE THREAD

**Issue by shawnemhe** [coreybutler/node-windows#273]
Npm audit is finding a [vulnerability in the minimist package](https://www.npmjs.com/advisories/1179).  This is coming through as a dependency of optimist. That package currently has a deprecation notice and is not likely to be updated. The package owner recommends using minimist directly, or nomnom.

Are there any efforts planned that would remediate this vulnerability?

**Comment by DevRCRun** [comment]
Snyk is flagging this for us too. There are some pull requests open to resolve, might be an idea to vote on the one you agree with

https://github.com/coreybutler/node-windows/pull/267

**Comment by shawnemhe** [comment]
@DevRCRun, I'll take a look at the PRs.

**Comment by coreybutler** [comment]
#267 is the one I will merge once it has been tested.

**Comment by seidhkona** [comment]
I see this issue has been fixed and merged, but optimist/minimist still appears as a dependency in the latest package version. Any update on that? Thanks!

**Comment by seidhkona** [comment]
Any plans on merging this anytime soon? Thanks!

**Comment by coreybutler** [comment]
Resolved with PR #267.
