### ISSUE TITLE
Windows service stops immediately <Security UserID="S-1-5-18" />

### ISSUE THREAD

**Issue by albertobura** [coreybutler/node-windows#275]
Hello,
thank you for the solution and the support.
I am facing the issue giving the title.
I prepared a nodejs app and installed as service, but it stops immediately on the windows 10.
As advised, I looked at TESTS.md, and tried the example and this behaves in the same way.

Would you have any advice?
Thank you in advance.

test.js

```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))`
```
install-windows-service.js
```
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'Node application as Windows Service',
  description: 'Node application as Windows Service',
  script: 'C:\\temp\\test.js'
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});
svc.install();
```

The Event viewer reports:
```
Log Name:      Application
Source:        Node application as Windows Service wrapper
Date:          26/10/2020 14:07:32
Event ID:      1000
Task Category: None
Level:         Warning
Keywords:      Classic
User:          SYSTEM
Computer:      DESKTOP-HEDL5EF.domain.local
Description:
C:\temp\test.js stopped running.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Node application as Windows Service wrapper" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-26T13:07:32.067536600Z" />
    <EventRecordID>194973</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-HEDL5EF.domain.local</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data>C:\temp\test.js stopped running.</Data>
  </EventData>
</Event>
```

**Comment by Avital103** [comment]
same here.

**Comment by coreybutler** [comment]
Does the script run without node-windows?  Running a web server on port 3000 should be fine, unless your user account is explicitly denied that ability, or if your firewall is blocking the service. The other possibility is a port conflict. If something else is running on port 3000, it would cause the server to crash.

For anyone who needs help figuring out whether anything is running on the same port, see https://github.com/coreybutler/porthog.

**Comment by albertobura** [comment]
Hello Corey,
Yes, if I start the script from cli, it works.
Thanks

**Comment by coreybutler** [comment]
Have you seen this? https://github.com/coreybutler/node-windows/wiki#my-script-installs-but-stops-after-a-few-seconds-why

Consider logging out the `process.env.USER` and/or `process.env.USERNAME` (or `os.userInfo()`) to validate the user under which the _service_ is running. I usually log this info to a text file from within the script if I suspect an issue with a user account, i.e. this would go in the top of your script. 

```javascript
fs.writeFileSync(path.join(process.cwd(), 'log.txt'), JSON.stringify(require('os').userInfo(), null, 2))
```

**Comment by coreybutler** [comment]
Closing as stale.
