### ISSUE TITLE
problem to list the processes

### ISSUE THREAD

**Issue by glerisonlima** [coreybutler/node-windows#276]
when executing the list command the feedback that shows me on the console is coming with an accent, how do I solve this?
![Screenshot_1](https://user-images.githubusercontent.com/13289584/98758376-64a85580-23ad-11eb-83c2-6a39121df35d.png)

**Comment by coreybutler** [comment]
The console may not support the character encoding of the text, but you can capture this text and output it using whatever encoding you want. In other words, modify the JSON object before logging it.
