### ISSUE TITLE
v1.0.0-beta.7 fails to start process

### ISSUE THREAD

**Issue by seidhkona** [coreybutler/node-windows#313]
This is already reported in Discussions, but I haven't found an open issue related to this. 

When I start the process using node-windows@1.0.0-beta.6 - the service is created and starts.
If I upgrade to node-windows@1.0.0-beta.7 - the service is created, but will not start: Error: 1067

**Comment by coreybutler** [comment]
It's not easy to tell based on the title of the other issue, but this is a duplicate of #308.
