### ISSUE TITLE
Clarification on how services are created / necessary permissions

### ISSUE THREAD

**Issue by dbronin** [coreybutler/node-windows#320]
Hello,

Running into a problem where windows crashes creating the service. This worked just fine before, but, due to security changes on the server (do not know what changes were made), the wrapper is now crashing.

Two questions:
1. Does the process use psexesvc.exe?
2. Can anyone point me in the right direction on what permissions are absolutely required on a windows server for this to work properly (besides full folder permissions on the folder containing the install / uninstall script).

Right now, the closest I've come to understanding the problem is this error when uninstalling the service: "Error: EPERM: operation not permitted".

Environment:
node-windows: 0.1.14
Node: 8.12
Server: Window Server 2016

Thank you so much!

**Comment by coreybutler** [comment]
> Two questions:
> 
> 1. Does the process use psexesvc.exe?
> 2. Can anyone point me in the right direction on what permissions are absolutely required on a windows server for this to work properly (besides full folder permissions on the folder containing the install / uninstall script).

1. No, psexecsvc.exe is not used by node-windows.
2. This depends (see below).

The absolute minimum requirements are execute permissions for the installed `.exe` file and write permissions on the directory (for logging). That would be enough to run a hello world process. IT sounds like you already have that though.

Most permissions challenges are rooted in the application itself. For example, if the application runs an HTTP server, it must have permission to run on a specific port. Ports under 1024 can sometimes be locked down. If the app needs to write to a different directory, it needs permission. Some strict Windows environments will block unsigned executables from running. Personally, I've run into issues with Windows Security Protected Folders, when it immediately kills some executables.

The `EPERM` error means the service user doesn't have permission to perform an operation. The operation would be something in the application code.

**Comment by dbronin** [comment]
Thank you so much for the quick response. 

The issue here is that the crash happens while the service is being created (or so it would seem - no entry in services appears); the actual application does not even have a chance to start. This same exact setup works perfectly across a number of other Windows Server 2016 machines that do not have the same permission limitations (whatever they are).

Can you tell me what executable files, besides winsw.exe, are involved in the process? 

Again, thank you so much!

**Comment by dbronin** [comment]
Thank you again! This definitely helps. I'll investigate further and report back here.

**Comment by dbronin** [comment]
Just for posterity, VM's Carbon Black does something that prevents this from properly creating a service. FYI for anyone else that encounters this issue and has Carbon Black installed.
