### ISSUE TITLE
[question] err.log and out.log has size limited?

### ISSUE THREAD

**Issue by radiorz** [coreybutler/node-windows#322]
**Issue:**

**How To Reproduce:**

start node-windows server
in daemon the err.log and out.log will save the logs of service. 
but it seems that it could not contain too much logs.

**Expected Behavior:**

I can choose the size of logs

**Desktop:**
 - OS: windows

**Comment by coreybutler** [comment]
node-windows has no constraints on the log size, but winsw does. This can be overridden using the `logging` configiuration attribute in the server.

For example:

```javascript
var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\path\\to\\helloworld.js',
  logging: {
    mode: 'roll-by-size', 
    sizeThreshold: 10240,    // <--- change this
    keepFiles: 8
  },
  nodeOptions: [
    '--harmony',
    '--max_old_space_size=4096'
  ]
  //, workingDirectory: '...'
  //, allowServiceLogon: true
});
```

The logging configuration options are passed straight to the winsw XML configuration. You can see more options in the function comments at https://github.com/coreybutler/node-windows/blob/master/lib/winsw.js#L20-L23
