### ISSUE TITLE
having windows authentication issue with Sequalize library

### ISSUE THREAD

**Issue by vigneswarandavarapu** [coreybutler/node-windows#333]
**Issue:**
Actually for my node js application i am trying to connect data bases without password approach (with windows authentication). i have prepared Sequalize connection object like below. with the normal approach i can able to connect. but with node-windows application. i am unable to connect. 

```
const sequelize = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'msnodesqlv8/lib/sequelize',
  dialectOptions: {
    options: {
      driver: '',
      connectionString: `Server=${config.get('app.dbConfig.server')};Database=${config.get('app.dbConfig.database')};Trusted_Connection=yes;`,
      trustedConnection: true,
      instanceName: ''
    }
  }
})
```

if i try connect data base with the node-windows i am reciveing mssql authentication issues, like below. 

```
{
	"status": "ERROR",
	"message": "File not found",
	"response": {
		"name": "SequelizeConnectionError",
		"parent": {
			"sqlstate": "28000",
			"code": 18456,
			"severity": 0,
			"serverName": "",
			"procName": "",
			"lineNumber": 0
		},
		"original": {
			"sqlstate": "28000",
			"code": 18456,
			"severity": 0,
			"serverName": "",
			"procName": "",
			"lineNumber": 0
		}
	}
}
```

could you please help me to resolve with this node-windows module

**Comment by coreybutler** [comment]
Please see [the wiki](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why). Judging by the error, it sounds like you probably need to specify an absolute path to a file in your app (or a config file used by sequelize). I don't use sequelize, but I suspect the `dialectModulePath` needs to be an absolute path instead of a relative one.

**Comment by vigneswarandavarapu** [comment]
I have gone through your Reference. but also tried by giving absolute path in the `dialectModulePath`. that also giving same error. and i noticed one thing in this module, if i try to give account credentials to this service. 
```
svc.logOnAs.account='XXXXXXXX';
svc.logOnAs.password='XXXXXXXX';
svc.logOnAs.domain='XXXXXXXXXXXXXX';
```

response got changed like below

`Error: Couldn't connect to server`

it might be helpful to you to resolve my issues

**Comment by coreybutler** [comment]
The error in your first post is telling you it cannot find a file, which I assume contains the connection string to the database. The error in your second post states it cannot _connect_ to the server, not that it can't _authenticate_ with the server. Bottom line: there isn't enough information to know _why_ sequelize cannot connect to the database.

Unfortunately, I don't have time to troubleshoot individual project issues. However; if you can identify a specific bug in this library, I can either provide a fix or mark the issue as "needs help" for someone to provide a PR.

**Comment by vigneswarandavarapu** [comment]
@coreybutler , Thank you for your help. actually this issue is fixed after giving proper access to the service which is generated by nodewindows from the windows service GUI. now it's working thank you.
