### ISSUE TITLE
Execute npm start

### ISSUE THREAD

**Issue by pols63** [coreybutler/node-windows#334]
Hi: Is it possible to execute "npm start" or "npm run script" with this package?

Thanks!

**Comment by coreybutler** [comment]
Not directly with this package, but your script can use a child process to execute any command it wants.

**Comment by AkashRajvanshi** [comment]
can you provide an example, how can I achieve this using scripts?

**Comment by miquelfire** [comment]
For script, you would make a .js (or .mjs or .cjs) file for the service to run, and use [child process](https://nodejs.org/api/child_process.html) to run the NPM command

Non ESM version I just pulled from a random SO answer:
```javascript
var child_process = require('child_process');
child_process.execSync('npm start',{stdio:[0,1,2]});
```

**Comment by miquelfire** [comment]
Full example for running a NPM script as a service

install.js
```
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name: 'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\Path\\To\\Your\\Project\\Root\\hello-world\\app.js', 
  env: {
    name: "NODE_ENV",
    value: "production"
  }
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install', function() {
  svc.start();
});

// Just in case this file is run twice.
svc.on('alreadyinstalled', function() {
  console.log('This service is already installed.');
});

// Install the script as a service.
svc.install();
```

runnpm.js
```
let child_process = require('child_process');
child_process.execSync('npm start',{stdio:[0,1,2]});
```

I don't know `child_process` enough to give an example, but you could edit runnpm.js to multiple NPM commands.
