### ISSUE TITLE
03/30/2023: Please release a non-beta version

### ISSUE THREAD

**Issue by grmcpna** [coreybutler/node-windows#344]
The readme states: "_This library can be used to install/start/stop/uninstall Node scripts as Windows background services for **production** environments. This is not a tool for developing applications, it is a tool for releasing them._"

Unfortunately latest release is still a beta which makes it difficult to use in a production environment.  Could this please be released as a non-beta?

**Comment by coreybutler** [comment]
The "beta" is production-grade. It powers millions services. It's only named as a beta because of a rollback. I'll drop the beta name in the next maintenance release.

**Comment by grmcpna** [comment]
I understand that it is production-grade but having beta in the name is causing issues with our internal approval process.  Thank you for the quick response!
