### ISSUE TITLE
Event Logging other than event id 1000

### ISSUE THREAD

**Issue by MarcRohrer** [coreybutler/node-windows#352]
Hi,

I would like to write specific event ids to be able to easily identify the problem when something goes wrong. The standard id 1000 works flawlessly, but eg.

log.info('beginning of program, initializing...', 1001)

results in windows popping up a message that the program wants to change the system for a user defined event and no entry is written.

I am not sure, if I am doing something wrong...
maybe?

Thanx!

Marc Rohrer

**Comment by miquelfire** [comment]
Looking at how events are created in the code, I saw it used eventcreate. Looking at the docs, I noticed something that might be key: It seems the ID can only be between 1 and 1000.

From [here](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/eventcreate)
> /id &lt;eventID> 	Specifies the event ID for the event. A valid ID is any number from 1 to 1000.

**Comment by MarcRohrer** [comment]
Interesting, but very strange. In my event log, I see tons of event ids higher than 1000.
Maybe a limitation of eventcreate.
But for differentiaton purposes, the absolute value does not really matter, I guess, as the id is to be interpreted in relation to the event source, right?
I checked with 700, which worked fine.
You might consider adding to the documentation:

a) eventcreate is used under the hood
b) this limits a custom event id to an unsigned int < 1000

Thank you very much for your input!

**Comment by miquelfire** [comment]
It would be int <= 1000

**Comment by MarcRohrer** [comment]
@miquelfire: so the id can be negative also?
according to the first post by [coreybutler] the expected data type is Uint32. So this shouldn't really work.
As the default is 1000, a custom value would be something other than 100, wouldn't it?

@coreybutler: future users will thank you for that :-)

**Comment by miquelfire** [comment]
The valid values are 1 to 1000. I assume if there was direct access to the event log API instead of using eventcreate, we could use higher values.
