### ISSUE TITLE
How to set service working directory?

### ISSUE THREAD

**Issue by sergeibelov** [coreybutler/node-windows#36]
winsw has an optional parameter called [workingdirectory](https://github.com/kohsuke/winsw#workingdirectory) which sets the current directory of the service. 

How can it be set in node-windows?

**Comment by boysmovie** [comment]
any update on this?

**Comment by coreybutler** [comment]
The daemon manager code never ended up getting released, so this never got fixed. I'd accept a PR on it.

**Comment by JoseIgnacio92** [comment]
https://github.com/coreybutler/node-windows/issues/225

**Comment by dustingraham** [comment]
I didn't want to do the `process.chdir(__dirname);` option. Found I could set `svc._directory` after initializing the Service object. More code in issue 225.

**Comment by coreybutler** [comment]
This is in master (per issue #225).
