### ISSUE TITLE
07/16/2024: Usage with typescript project

### ISSUE THREAD

**Issue by rojithaDev** [coreybutler/node-windows#378]
**Is your feature request related to a problem? Please describe.**
Only work with javascript projects. 

**Describe the solution you'd like**
Ability to use it with projects with ts extensions.

**Describe alternatives you've considered**
No alternatives are available: Please include in comments if there is one.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
This is not a compiler. Use `tsc` to compile your code like you would any other TS project. Specify the output of your compilation process as the source of your executable.

**Comment by rojithaDev** [comment]
> This is not a compiler. Use `tsc` to compile your code like you would any other TS project. Specify the output of your compilation process as the source of your executable.

I'm a bit confused about this.
After I compile the project with tsc, I have my dist folder with all my compiled files and the entry file `index.js` 

I tried:
```
import { Service } from 'node-windows'

const svc = new Service({
  name: "Service",
  description: "Test Service",
  script: "C:\\Users\\testUser\\Documents\\testProject\\dist\\index.js",
});

svc.on("install", () => {
  svc.start();
});

svc.install();
```
Then I install this service. However this service just crashes without any errors reported to the logs.
