### ISSUE TITLE
32 or 64 bit (doc bug)

### ISSUE THREAD

**Issue by gcoon151** [coreybutler/node-windows#379]
**Issue:**
Docs/GH Readme don't make clear if the node.js env that comes up has access to 64 bit levels of memory or 32 only. 

**How To Reproduce:**
Google for node-windows 64 bit or 32 bit? Browse through repo trying to see if the env is 32 or 64 bit node. 

**Expected Behavior:**
Apologies for making this a bug. This just seemed the best way to send the feedback.

**Comment by miquelfire** [comment]
For the purpose of this project, it's based on the version of Node.js installed.
