### ISSUE TITLE
Option to set Startup Type on Service Install?

### ISSUE THREAD

**Issue by ZaLiTHkA** [coreybutler/node-windows#53]
As the title suggests, I'm looking for a way to set the service "Startup Type" option when I install my service.. Is that possible with this package?

I had a look at the functionality from `winsw.exe` and I don't see it there, but just to confirm... Would this sort of option rely on a feature from winsw, or am I missing something simple here?

**Comment by dannyrich** [comment]
This looks like startmode is now available in winsw.exe:

https://github.com/kohsuke/winsw#startmode---optional-element
https://github.com/kohsuke/winsw/commit/57b6d2ad484698cdeadbd7494c920331775af2f5
