### ISSUE TITLE
Strange issue?

### ISSUE THREAD

**Issue by cdurth** [coreybutler/node-windows#70]
Trying to track down an issue, not sure if it is windows related, or directly related to this.

I created an install script. Ran fine, service was created, service started. 
I then manually killed the service process.
Now, when i try to start the service, it attempts to start, but fails.
EventViewer doesnt provide much "The MWA-WebRegistration service terminated unexpectedly.  It has done this 1 time(s)." (nothing more in details section)
I have uninstalled the service, and tried reinstalling with no luck.

I am new to windows services so I am not sure if this is a windows bug, or an application bug.

Any help appreciated

**Comment by coreybutler** [comment]
I've added a [wiki entry](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why) compiling reasons for this type of scenario.
