### ISSUE TITLE
Gracefull script termination

### ISSUE THREAD

**Issue by braytak** [coreybutler/node-windows#75]
**Usage question** - what is the best way to get a service **script** to terminate gracefully i.e. give the script the opportunity to go through its termination chores. 

I have tried setting up a service *stop* listener (using the same *name* and *script* arguments used for service installation) within the script, but the listener does not seem to get called.

Any guidance would be welcome!

**Comment by ralphmason** [comment]
I am looking for the otherway around.  Someone stops the service so you need your app to gracefully exit.

On liunx / osx I can catch SIGINT and do a graceful shutdown in my app, is there anything the same for apps running as a windows service?

**Comment by coreybutler** [comment]
@ralphmason - I never saw your question. If it's still something worth addressing, please open a new issue.
