### ISSUE TITLE
NODE_ENV - how to set it?

### ISSUE THREAD

**Issue by christianalfoni** [coreybutler/node-windows#8]
Hi,

Great module, but how do I set f.ex. NODE_ENV=production?

Normally on windows you do it on the commandline with SET NODE_ENV=production, but I  can not figure out how to do it with this module.

Thanks

**Comment by FoldZero** [comment]
This seems to have dropped from the guides, lucky i found this old post! Im now working with a functional NODE_ENV
The guide i followed was  [here](https://www.npmjs.com/package/node-windows), n
