### ISSUE TITLE
Passing arguments to the node

### ISSUE THREAD

**Issue by Superlukec** [coreybutler/node-windows#80]
Is it possible to pass arguments to node script?

For example (using node):
```javascript
node server.js hello
```
In this case "hello" is the passing argument.

Thank you for your help,
Cheers

**Comment by PhilHannent** [comment]
Reading the documentation it looks like you can do that via the environment variables, they apply just to the run of service:

https://github.com/coreybutler/node-windows#environment-variables

    env: {
        name: "ENV_HELLO",
        value: "hello"
    }

You could then read the variable:

    process.env.ENV_HELLO

You could code for reading the arguments, if they are empty you then check the env.

The method appears to be used internally:
https://github.com/coreybutler/node-windows/blob/master/lib/daemon.js#L53

**Comment by Superlukec** [comment]
Nice. It works, thank you very much!
