### ISSUE TITLE
Service startup directory

### ISSUE THREAD

**Issue by barakSpoj** [coreybutler/node-windows#81]
Hi,

I wanted to know if there is a way to configure the startup directory for the service executable.

Thanks,
Barak

**Comment by coreybutler** [comment]
Are you talking about the node executable (i.e. [Script Envrionement Variable](https://github.com/coreybutler/node-windows#environment-variables) or the `daemon` directory? The `daemon` directory is not configurable from the script, but you can change it after the install.

**Comment by barakSpoj** [comment]
Got it, thanks
