### ISSUE TITLE
Does it work on windows XP?

### ISSUE THREAD

**Issue by vinicius0026** [coreybutler/node-windows#82]
When running on Windows XP, I get an error: "node.exe - Application Error - The application falied to initialize properly (0xc0000135). Click on Ok to terminate the application.". I'm running as Administrator.

**Comment by coreybutler** [comment]
I know there are other users who have successfully used this on XP, but (as I'm sure you've seen from the other issues), this has not been tested on XP, nor is it supported on any product that has reached EOL with Microsoft.
