### ISSUE TITLE
Compatible with edge.js?

### ISSUE THREAD

**Issue by dingjing** [coreybutler/node-windows#87]
I have a node.js web app calling a PowerShell script using edge.js. When the app is started with "node myApp", it works fine. When it is started as a service using node-windows, it skips the calling PowerShell part.

**Comment by coreybutler** [comment]
I've never used edge.js, so I don't know how it's working. However; I have compiled a short list of the [most common reasons](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why) for this type of behavior. I suspect you're using a relative path in your install script that isn't being translated properly.
