### ISSUE TITLE
Property not defined for config

### ISSUE THREAD

**Issue by mmacintosh-ap** [coreybutler/node-windows#93]
Node-windows doesn't seem to be finding configuration files when using node-config. First there is a warning about nor finding any config files in C:\Windows\System32\config, followed by a Configuration Property "<some property>" is not defined. The application works fine when running from commandline, node app.js, but crashes after starting as a windows service with the errors in the .err.log file for the daemon.

WARNING: No configurations found in configuration directory:
WARNING: C:\Windows\system32\config
...
Error: Configuration property "Logging" is not defined

**Comment by coreybutler** [comment]
Have you seen [My Script runs fine on it's own but not with node-windows. Why?](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why)

**Comment by mmacintosh-ap** [comment]
Thanks I did see that. I was able to figure this out by adding the NODE_CONFIG_DIR environment variable to the service install script. 

  env: [
	{name:"NODE_CONFIG_DIR", value: "FULL_PATH_TO_CONFIG_DIR"}	
  ]

**Comment by coreybutler** [comment]
Great, glad you got it working!
