### ISSUE TITLE
Write files function failed. 

### ISSUE THREAD

**Issue by timeislife** [coreybutler/node-windows#94]
I am using multer for uploading attachment, and winston for logging. 
Whitout using node-windows, I open command line, and run node app.js, both uploading and logging works. 
After using node-windows, uploading and logging fails and no physical files are created. It seems that no write permission. 
Here is my install script:
--------------------------------------
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'MySystemAutoStart',
  description: 'auto start my System',
  script: require('path').join(__dirname,'app.js')
});

svc.user.domain = 'domain';
svc.user.account = 'username';
svc.user.password = 'password';

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});
svc.install();
----------------------------------

I also tried whithout using user name and password, and tried change the service's logon user name and password in Services UI ,and all failed. 

Can anyone tell me how to use node-windows and get write permission for the folders?
thanks.

**Comment by coreybutler** [comment]
Have you seen [My script runs fine on its own but not with node-windows. Why?](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why)

**Comment by timeislife** [comment]
@coreybutler
it is just what I am looking for, it solves my problem. thank you so much!
