### ISSUE TITLE
workingdirectory not carried from configuration to xml. bug?

### ISSUE THREAD

**Issue by vaughanatworld** [coreybutler/node-windows#96]
aurthur blake fork; daemon.js line 373: suggested fix:

    workingdirectory: {
      enumerable: false,
      writable: true,
      configurable: false,
      value: config.workingdirectory || process.cwd()
    },

**Comment by coreybutler** [comment]
This should really be directed to @arthurblake, since this is only in his code base.

**Comment by JoseIgnacio92** [comment]
https://github.com/coreybutler/node-windows/issues/225
