### ISSUE TITLE
I think I'm missing something...

### ISSUE THREAD

**Issue by padillah** [coreybutler/node-windows#97]
I cannot get anything to work but the npm install.

I ran "npm install -g node-windows" from a CLI and it worked. That's all I can do. I have no idea what scripts you are writing. No clue how to run those scripts. I've tried running them as js scripts, I've tried "java.exe install.js", I've tried "WScript.exe install.js", I've tried using PowerShell...

Please walk me through what is, apparently, so obvious it doesn't even need to be mentioned. From a CLI window, on Windows 8.1 how do I use this product? What do I actually type and where do I type it? "Run the script" is not as intuitive as you might think.

**Comment by arthurblake** [comment]
It's a nodejs library. Try "node <script.js>"

**Comment by arthurblake** [comment]
Sorry let me back up. It's a nodejs library, so you need to incorporate it into your own node js program and run it with nodejs or iojs on windows. You provide the program in whatever way you need to use it. The example in the README are very useful in getting that going.

**Comment by padillah** [comment]
OK, I came here looking for a way to run TiddlyWiki as a service. That doesn't sound like what this is for. Thanks for the info. It looks like I was trying to do the wrong thing.

**Comment by arthurblake** [comment]
With a little bit of programming you might be able to get it to work but no it's not an out-of-box solution.
